{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoError","stack":"MongoError: failed to connect to server [127.0.0.1:27017] on first connect\n    at Pool.<anonymous> (/Users/medeaohm/Desktop/Github/iOS-App-ChallengeAccepted/ChallengeAcceptedServer/node_modules/mongodb-core/lib/topologies/server.js:326:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:191:7)\n    at Connection.<anonymous> (/Users/medeaohm/Desktop/Github/iOS-App-ChallengeAccepted/ChallengeAcceptedServer/node_modules/mongodb-core/lib/connection/pool.js:270:12)\n    at Object.onceWrapper (events.js:293:19)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:194:7)\n    at Socket.<anonymous> (/Users/medeaohm/Desktop/Github/iOS-App-ChallengeAccepted/ChallengeAcceptedServer/node_modules/mongodb-core/lib/connection/connection.js:175:49)\n    at Object.onceWrapper (events.js:293:19)\n    at emitOne (events.js:96:13)","level":"warn","timestamp":"2017-03-28T16:17:38.556Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoError","stack":"MongoError: failed to connect to server [127.0.0.1:27017] on first connect\n    at Pool.<anonymous> (/Users/medeaohm/Desktop/Github/iOS-App-ChallengeAccepted/ChallengeAcceptedServer/node_modules/mongodb-core/lib/topologies/server.js:326:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:191:7)\n    at Connection.<anonymous> (/Users/medeaohm/Desktop/Github/iOS-App-ChallengeAccepted/ChallengeAcceptedServer/node_modules/mongodb-core/lib/connection/pool.js:270:12)\n    at Object.onceWrapper (events.js:293:19)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:194:7)\n    at Socket.<anonymous> (/Users/medeaohm/Desktop/Github/iOS-App-ChallengeAccepted/ChallengeAcceptedServer/node_modules/mongodb-core/lib/connection/connection.js:175:49)\n    at Object.onceWrapper (events.js:293:19)\n    at emitOne (events.js:96:13)","level":"warn","timestamp":"2017-03-28T16:17:38.569Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoError","stack":"MongoError: failed to connect to server [127.0.0.1:27017] on first connect\n    at Pool.<anonymous> (/Users/medeaohm/Desktop/Github/iOS-App-ChallengeAccepted/ChallengeAcceptedServer/node_modules/mongodb-core/lib/topologies/server.js:326:35)\n    at emitOne (events.js:96:13)\n    at Pool.emit (events.js:191:7)\n    at Connection.<anonymous> (/Users/medeaohm/Desktop/Github/iOS-App-ChallengeAccepted/ChallengeAcceptedServer/node_modules/mongodb-core/lib/connection/pool.js:270:12)\n    at Object.onceWrapper (events.js:293:19)\n    at emitTwo (events.js:106:13)\n    at Connection.emit (events.js:194:7)\n    at Socket.<anonymous> (/Users/medeaohm/Desktop/Github/iOS-App-ChallengeAccepted/ChallengeAcceptedServer/node_modules/mongodb-core/lib/connection/connection.js:175:49)\n    at Object.onceWrapper (events.js:293:19)\n    at emitOne (events.js:96:13)","level":"warn","timestamp":"2017-03-28T16:17:38.570Z"}
